name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

env:
  BIN_NAME: sfm

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x86_64
            bin_suffix: ""

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Compress with UPX
        run: upx --best --lzma target/release/${{ env.BIN_NAME }}${{ matrix.bin_suffix }}

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p dist
          FILE_NAME=${{ env.BIN_NAME }}-${{ matrix.platform }}${{ matrix.bin_suffix }}
          mv target/release/${{ env.BIN_NAME }}${{ matrix.bin_suffix }} dist/$FILE_NAME

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.platform }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
